---
# DNS Record Configuration Package
# Provides XRD and Composition for DNS record management
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-dns-record
  namespace: crossplane-system
spec:
  package: ghcr.io/open-service-portal/configuration-dns-record:v1.0.2

  # Package pull policy
  # IfNotPresent: Only download if not in cache (recommended for production)
  # Always: Check for updates on reconciliation (useful for development)
  packagePullPolicy: IfNotPresent

  # Revision activation policy
  # Automatic: New revisions become active immediately (good for single-tenant)
  # Manual: Requires manual activation (safer for multi-tenant production)
  revisionActivationPolicy: Automatic

  # Number of inactive revisions to keep
  # Useful for rollback scenarios
  revisionHistoryLimit: 3

  # Skip dependency resolution
  # Set to true if providers are pre-installed in the cluster
  skipDependencyResolution: true
