# Cloudflare DNS Record Template
# Provides real DNS record management in Cloudflare
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: template-cloudflare-dnsrecord
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://github.com/open-service-portal/template-cloudflare-dnsrecord
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: template-cloudflare-dnsrecord
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: template-cloudflare-dnsrecord
  path: "./"
  prune: true
  targetNamespace: crossplane-system