---
# WhoAmI Service Configuration Package  
# Provides composite service with app + DNS
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-whoami-service
  namespace: crossplane-system
spec:
  package: ghcr.io/open-service-portal/configuration-whoami-service:v1.0.3
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 3
  skipDependencyResolution: true
