---
# WhoAmI Configuration Package
# Provides XRD and Composition for demo application deployment
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-whoami
  namespace: crossplane-system
spec:
  package: ghcr.io/open-service-portal/configuration-whoami:v1.0.3
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 3
  skipDependencyResolution: true
